INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Physics', 4, 'B+', 'M & W');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Biology', 3, 'A-', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('History', 3, 'B', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Chemistry', 4, 'A', 'M & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Philosophy', 3, 'A-', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Art', 2, 'B+', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Economics', 4, 'A', 'W & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Sociology', 3, 'B', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Literature', 3, 'A', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Political Science', 4, 'B+', 'M & W');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Statistics', 3, 'B-', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Geography', 2, 'A', 'M & W');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Psychology', 4, 'A-', 'M & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Music', 3, 'B+', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Anthropology', 4, 'A', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Astronomy', 3, 'A-', 'W & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Environmental Science', 4, 'B', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Business', 3, 'A', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Computer Science', 4, 'A-', 'M & W');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Drama', 2, 'B+', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Ethics', 3, 'B-', 'M & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Calculus', 5, 'A', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Microbiology', 4, 'B+', 'M & W');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Genetics', 3, 'A-', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Marketing', 4, 'A', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Finance', 3, 'B', 'W & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Accounting', 4, 'A-', 'M & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Journalism', 3, 'B+', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Nursing', 4, 'A', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Law', 3, 'A-', 'M & W');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Public Health', 4, 'B', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Pharmacy', 3, 'A', 'W & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Veterinary Science', 4, 'A-', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Engineering', 5, 'B+', 'M & W');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Architecture', 4, 'B-', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Graphic Design', 3, 'A', 'M & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Interior Design', 4, 'B+', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Fashion Design', 3, 'A-', 'W & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Film Studies', 4, 'A', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Photography', 2, 'B', 'M & W');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Theater', 3, 'A-', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Dance', 2, 'B+', 'M & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Culinary Arts', 4, 'A', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Hospitality', 3, 'B', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Tourism', 3, 'A-', 'M & W');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Sports Management', 4, 'B+', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Physical Education', 2, 'A', 'W & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Kinesiology', 3, 'B+', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Nutrition', 4, 'A-', 'M & W');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Dietetics', 3, 'A', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Clinical Psychology', 4, 'B', 'M & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Child Development', 3, 'A-', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Social Work', 4, 'B+', 'W & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Criminal Justice', 3, 'A', 'M & W');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Forensic Science', 4, 'B-', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Cybersecurity', 4, 'A-', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Information Systems', 3, 'B+', 'M & W');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Software Engineering', 4, 'A', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Network Administration', 3, 'B', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Web Development', 4, 'A-', 'W & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Mobile App Development', 3, 'A', 'M & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Game Design', 3, 'B+', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Database Management', 4, 'B-', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Artificial Intelligence', 4, 'A-', 'M & W');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Machine Learning', 3, 'A', 'online');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Data Science', 4, 'B+', 'M & F');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Cloud Computing', 3, 'A-', 'T & Th');
INSERT INTO MyClasses (courseName, Units, Grade, Day) VALUES ('Quantum Computing', 4, 'B', 'W & F');




