INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('John Doe', '123-456-7890', 'New York, NY', 'Friend from college');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Jane Smith', '234-567-8901', 'Los Angeles, CA', 'Work colleague');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Michael Johnson', '345-678-9012', 'Chicago, IL', 'Gym buddy');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Emily Davis', '456-789-0123', 'Houston, TX', 'Neighbor');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('David Martinez', '567-890-1234', 'Phoenix, AZ', 'Cousin');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Laura Wilson', '678-901-2345', 'San Antonio, TX', 'High school friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('James Brown', '789-012-3456', 'San Diego, CA', 'University professor');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Sophia Taylor', '890-123-4567', 'Dallas, TX', 'Yoga instructor');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Daniel Harris', '901-234-5678', 'San Jose, CA', 'Business partner');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Olivia Lewis', '012-345-6789', 'Austin, TX', 'Childhood friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('William Clark', '123-456-7891', 'San Francisco, CA', 'Tech conference contact');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Isabella Hall', '234-567-8902', 'Seattle, WA', 'Art class buddy');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Joseph Allen', '345-678-9013', 'Denver, CO', 'Mountain biking friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Mia Young', '456-789-0124', 'Portland, OR', 'Cooking class friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Alexander Scott', '567-890-1235', 'Miami, FL', 'Vacation friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Amelia Adams', '678-901-2346', 'Orlando, FL', 'Theme park buddy');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Ethan Baker', '789-012-3457', 'Las Vegas, NV', 'Casino acquaintance');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Charlotte Turner', '890-123-4568', 'Atlanta, GA', 'Volunteer friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Mason Rivera', '901-234-5679', 'Tucson, AZ', 'Hiking group friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Harper Wright', '012-345-6780', 'Albuquerque, NM', 'Photography classmate');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Liam King', '123-456-7892', 'Sacramento, CA', 'Political contact');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Ella Lee', '234-567-8903', 'Kansas City, MO', 'Food truck friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Noah Walker', '345-678-9014', 'Minneapolis, MN', 'Ice fishing buddy');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Ava Hernandez', '456-789-0125', 'St. Louis, MO', 'Music festival friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Lucas Green', '567-890-1236', 'Cincinnati, OH', 'Soccer league friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Mason Parker', '678-901-2347', 'Cleveland, OH', 'College roommate');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Sofia Nelson', '789-012-3458', 'Pittsburgh, PA', 'Volunteer group friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Oliver Carter', '890-123-4569', 'Philadelphia, PA', 'Basketball teammate');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Charlotte Mitchell', '901-234-5680', 'Columbus, OH', 'Tech meetup contact');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Benjamin Perez', '012-345-6781', 'Indianapolis, IN', 'Car club buddy');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Amelia Roberts', '123-456-7893', 'Milwaukee, WI', 'Book club friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('James Roberts', '234-567-8904', 'Oklahoma City, OK', 'Bowling league friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Grace Phillips', '345-678-9015', 'Louisville, KY', 'Running partner');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Henry Campbell', '456-789-0126', 'Nashville, TN', 'Music teacher');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Sofia Evans', '567-890-1237', 'Charlotte, NC', 'Dance class friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Jackson Rodriguez', '678-901-2348', 'Raleigh, NC', 'Basketball coach');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Olivia White', '789-012-3459', 'Richmond, VA', 'Photography group friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Lucas Jones', '890-123-4570', 'Norfolk, VA', 'Neighbor');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Mia Anderson', '901-234-5681', 'Virginia Beach, VA', 'Gym buddy');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Sebastian Moore', '012-345-6782', 'Jacksonville, FL', 'College friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Isabella Thomas', '123-456-7894', 'Tampa, FL', 'Travel buddy');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Aiden Gonzalez', '234-567-8905', 'New Orleans, LA', 'Jazz festival friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Emma Lopez', '345-678-9016', 'Baton Rouge, LA', 'High school friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Sophia Harris', '456-789-0127', 'Birmingham, AL', 'Church group friend');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('James Clark', '567-890-1238', 'Huntsville, AL', 'Fishing buddy');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Mason Wilson', '678-901-2349', 'Little Rock, AR', 'Work colleague');
INSERT INTO "PhoneBook" ("People", "Number", "Location", "Notes") VALUES ('Mia Young', '789-012-3460', 'Salt Lake City, UT', 'Hiking friend');

